
package com.brotherhui.cucumber.service.wsimport.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserRequestService", targetNamespace = "http://www.hifreud.com/webservice", wsdlLocation = "http://localhost:8443/ws/users.wsdl?wsdl")
public class UserRequestService
    extends Service
{

    private final static URL USERREQUESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERREQUESTSERVICE_EXCEPTION;
    private final static QName USERREQUESTSERVICE_QNAME = new QName("http://www.hifreud.com/webservice", "UserRequestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8443/ws/users.wsdl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERREQUESTSERVICE_WSDL_LOCATION = url;
        USERREQUESTSERVICE_EXCEPTION = e;
    }

    public UserRequestService() {
        super(__getWsdlLocation(), USERREQUESTSERVICE_QNAME);
    }

    public UserRequestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERREQUESTSERVICE_QNAME, features);
    }

    public UserRequestService(URL wsdlLocation) {
        super(wsdlLocation, USERREQUESTSERVICE_QNAME);
    }

    public UserRequestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERREQUESTSERVICE_QNAME, features);
    }

    public UserRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserRequestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserRequest
     */
    @WebEndpoint(name = "UserRequestSoap11")
    public UserRequest getUserRequestSoap11() {
        return super.getPort(new QName("http://www.hifreud.com/webservice", "UserRequestSoap11"), UserRequest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserRequest
     */
    @WebEndpoint(name = "UserRequestSoap11")
    public UserRequest getUserRequestSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hifreud.com/webservice", "UserRequestSoap11"), UserRequest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERREQUESTSERVICE_EXCEPTION!= null) {
            throw USERREQUESTSERVICE_EXCEPTION;
        }
        return USERREQUESTSERVICE_WSDL_LOCATION;
    }

}
