
package com.brotherhui.cucumber.service.wsimport.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserRequest", targetNamespace = "http://www.hifreud.com/webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserRequest {


    /**
     * 
     * @param userRequest
     * @return
     *     returns com.brotherhui.wsimport.UserResponse
     */
    @WebMethod(operationName = "User")
    @WebResult(name = "UserResponse", targetNamespace = "http://www.hifreud.com/ws/demo", partName = "UserResponse")
    public UserResponse user(
        @WebParam(name = "UserRequest", targetNamespace = "http://www.hifreud.com/ws/demo", partName = "UserRequest")
        UserRequest_Type userRequest);

}
